<style>
.dd{
    padding-left: 20px;
}
p{
    margin: 10px 0;
}
</style>
<div class="wpb_text_column wpb_content_element">
<img src="<?= RES_URL; ?>newClient/img/slider/slider1 (4).jpeg" class="img-fluid terms-pricy-banner" alt="Responsive image">
		<div class="wpb_wrapper container privacy-page">
			<ol>
<li class="dd">This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.</li>
<li class="dd">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy is maintained by the DHVANI_ADD_GROUPS (sales promotion and the advertiser).</li>
</ol>
<h4><u>Interpretation and Definitions:</u></h4>
<h4><i>Interpretation:</i></h4>
<p align="justify">The words of which the initial letter is capitalized have meanings defined under the following conditions.<br>
The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h4><i>Definitions:</i></h4>
<p align="justify"><b>For the purposes of this Privacy Policy:</b></p>
<ul>
<li>You mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
<li>Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to DHVANI_ADD_GROUPS (sales promotion and the advertiser), Rajkot.</li>
<li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
<li>Account means a unique account created for You to access our Service or parts of our Service.</li>
<li>Website refers to Dhvani Add Groups, accessible from <a href="https://www.dhvaniaddgroups.com/"><b><span class="sitecolor">www.dhvaniaddgroups.com</span></b></a></li>
<li><b>Country refers to:</b> Gujarat, India</li>
<li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
<li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
<li>Personal Data is any information that relates to an identified or identifiable individual.</li>
<li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
<li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
</ul>
<h4><u><b>Collecting and Using Your Personal Data:</b></u></h4>
<h4><i><b>Types of Data Collected:</b></i></h4>
<p align="justify"><b><i>Personal Data:</i></b></p>
<ol>
<li class="dd"><b>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</b></li>
</ol>
<ul class="dd">
<li>Email address</li>
<li>First name and last name</li>
<li>Phone number</li>
<li>Address, State, Province, ZIP/Postal code, City</li>
<li>Usage Data</li>
</ul>
<p align="justify"><b><i>Usage Data:</i></b></p>
<ul>
<li>Usage Data is collected automatically when using the Service.</li>
<li>Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</li>
<li>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</li>
<li>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</li>
</ul>
<p align="justify"><b><i>Tracking Technologies and Cookies: </i></b></p>
<ul>
<li>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</li>
<li>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
<li>Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</li>
<li><b>We use both session and persistent Cookies for the purposes set out below:</b></li>
</ul>
<p align="justify"><i>Necessary / Essential Cookies</i></p>
<p align="justify"><b>Purpose:</b> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
<p align="justify">Cookies Policy / Notice Acceptance Cookies</p>
<p align="justify"><b>Purpose:</b> These Cookies identify if users have accepted the use of cookies on the Website.</p>
<p align="justify"><b>Functionality Cookies:</b></p>
<p align="justify"><b>Purpose:</b> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
<p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.</p>
<h4><u>Use of Your Personal Data:</u></h4>
<p align="justify"><b>The Company may use Personal Data for the following purposes:</b></p>
<ul>
<li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
<li><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
</ul>
<p align="justify"><b><i>For the performance of a contract:</i></b></p>
<p align="justify">the development, compliance and undertaking of the contract for the services you have registered or enrolled or of any other contract with Us through the Service.</p>
<p align="justify"><b><i>To contact You:</i></b></p>
<p align="justify">To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
<p align="justify"><b><i>To provide You:</i></b></p>
<p align="justify">with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
<p align="justify"><b><i>To manage Your requests:</i></b></p>
<p align="justify"><b>We may share your personal information in the following situations:</b></p>
<p align="justify"><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to show advertisements to You to help support and maintain Our Service, to contact You, to advertise on third party websites to You after You visited our Service or for payment processing.</p>
<p align="justify"><b>For Business transfers:</b> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</p>
<p align="justify"><b>With Affiliates:</b> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
<p align="justify"><b>With Business partners:</b> We may share Your information with Our business partners to offer You certain products, services or promotions.</p>
<p align="justify"><b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see You name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</p>
<h4><u>Retention of Your Personal Data:</u></h4>
<p align="justify">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p align="justify">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
<h4><u>Transfer of Your Personal Data:</u></h4>
<p align="justify">Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
<p align="justify">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p align="justify">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h4 align="justify"><u>Privacy Policy for Online Payment &amp; Transactions:</u></h4>
<p align="justify">Company is using the services of Razorpay, a fincial technology company providing services of online/internet payments and transactions. The privacy policy of Razorpay <a href="https://razorpay.com/privacy/" target="_blank" rel="noopener noreferrer"><b><span class="sitecolor">(https://razorpay.com/privacy/)</span></b></a> with regard to payment on Company’s website shall be applicable.</p>
<h4 align="justify"><u>Disclosure of Your Personal Data:</u></h4>
<p align="justify"><b><i>Business Transactions:</i></b></p>
<p align="justify">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<p align="justify"><b><i>Law enforcement:</i></b></p>
<p align="justify">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<p align="justify"><b><i>Other legal requirements:</i></b></p>
<p align="justify"><b>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</b></p>
<p align="justify"><b>Comply with a legal obligation:</b></p>
<ul>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<p align="justify"><b><i>Security of Your Personal Data:</i></b></p>
<p align="justify">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<p align="justify"><b><i>Children’s Privacy:</i></b></p>
<p align="justify">Our Service also address the Child under the age of 13. We are collecting personally identifiable information of child under the age of 13. If You are a parent or guardian and if You have concern with Your child’s information provided to Us, please contact Us.</p>
<p align="justify">We strictly limit the personal information that is publicly viewable about a member who is known by us to be a Child. Usernames of Children who are under 13 are not posted with this submitted content on our Sites. Although the Child may create a Profile for his or her account (which includes only a username, password, birth month and year, and parent’s email address), no portion of the Child’s Profile other than the Child’s age is publicly viewable.</p>
<p align="justify">We also may limit how We collect, use, and store some of the information of Users between 13 and 18 years old. In some cases, this means We will be unable to provide certain functionality of the Service to these users.</p>
<p align="justify"><b>We do not disclose to third parties any Children’s personal information that we collect other than as follows, consistent with applicable law:</b> (a) with a parent’s permission, (b) as required by any applicable law, (c) to third-party service providers who help us operate or manage the Sites, (d) as part of aggregated data shared with third-party service providers, our Board of Directors, funders and other partners, as described in the Privacy Policy, (e) to comply with legal process, (f) to respond to governmental requests, (g) to enforce our Terms of Service, (h) to protect our operations, (i) for assistance in fraud detection and prevention; (j) to protect the rights, privacy, safety or property of Common Sense Media, your Child or others, (k) to permit us to pursue available remedies or limit the damages that we may sustain, and (l) in connection with a disposition of all or a substantial portion of our business, assets or stock, such as a sale, merger, consolidation, reorganization, joint venture, assignment, or bankruptcy or similar proceedings.</p>
<p align="justify">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.</p>
<p align="justify"><b><i>Links to Other Websites:</i></b></p>
<p align="justify">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p align="justify">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<p align="justify"><b><i>Changes to this Privacy Policy:</i></b></p>
<p align="justify">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p align="justify">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.</p>
<p align="justify">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h4><u>Contact Us:</u></h4>
<p align="justify"><b>If you have any questions about this Privacy Policy, You can contact us:</b></p>
<p align="justify">By mail: <a href="mailto:info@dhvaniaddgroups.com"><b><span class="sitecolor">info@dhvaniaddgroups.com</span></b></a></p>

		</div>
	</div>
